'use strict';

angular.module('gisto.service.syntaxRepository', [], function ($provide) {
    $provide.service('syntaxRepository', function () {
        var syntax = {
            syntaxes: {
                ABAP: "abap",
                ActionScript: "actionscript",
                Ada: "ada",
                Agda: "text",
                "AGS Script": "c_cpp",
                Alloy: "text",
                "Ant Build System": "xml",
                ANTLR: "text",
                ApacheConf: "apache_conf",
                Apex: "java",
                APL: "text",
                AppleScript: "applescript",
                Arc: "text",
                Arduino: "c_cpp",
                AsciiDoc: "asciidoc",
                ASP: "text",
                AspectJ: "text",
                Assembly: "assembly_x86",
                ATS: "ocaml",
                Augeas: "text",
                AutoHotkey: "autohotkey",
                AutoIt: "autohotkey",
                Awk: "text",
                Batchfile: "batchfile",
                Befunge: "text",
                Bison: "text",
                BitBake: "text",
                BlitzBasic: "text",
                BlitzMax: "text",
                Bluespec: "verilog",
                Boo: "text",
                Brainfuck: "text",
                Brightscript: "text",
                Bro: "text",
                C: "c_cpp",
                "C#": "csharp",
                "C++": "c_cpp",
                "C-ObjDump": "assembly_x86",
                "C2hs Haskell": "haskell",
                "Cap'n Proto": "text",
                CartoCSS: "text",
                Ceylon: "text",
                Chapel: "text",
                ChucK: "java",
                Cirru: "cirru",
                Clean: "text",
                CLIPS: "text",
                Clojure: "clojure",
                CMake: "text",
                COBOL: "cobol",
                CoffeeScript: "coffee",
                ColdFusion: "coldfusion",
                "ColdFusion CFC": "coldfusion",
                "Common Lisp": "lisp",
                "Component Pascal": "pascal",
                Cool: "text",
                Coq: "text",
                "Cpp-ObjDump": "assembly_x86",
                Creole: "text",
                Crystal: "ruby",
                CSS: "css",
                Cucumber: "text",
                Cuda: "c_cpp",
                Cycript: "javascript",
                Cython: "text",
                D: "d",
                "D-ObjDump": "assembly_x86",
                "Darcs Patch": "text",
                Dart: "dart",
                Diff: "diff",
                DM: "c_cpp",
                Dockerfile: "dockerfile",
                Dogescript: "text",
                Dylan: "text",
                E: "text",
                Eagle: "xml",
                eC: "text",
                "Ecere Projects": "json",
                ECL: "text",
                edn: "clojure",
                Eiffel: "eiffel",
                Elixir: "elixir",
                Elm: "elm",
                "Emacs Lisp": "lisp",
                EmberScript: "coffee",
                Erlang: "erlang",
                "F#": "text",
                Factor: "text",
                Fancy: "text",
                Fantom: "text",
                fish: "text",
                FLUX: "text",
                Forth: "forth",
                FORTRAN: "text",
                Frege: "haskell",
                "G-code": "gcode",
                "Game Maker Language": "c_cpp",
                GAMS: "text",
                GAP: "text",
                GAS: "assembly_x86",
                GDScript: "text",
                Genshi: "xml",
                "Gentoo Ebuild": "sh",
                "Gentoo Eclass": "sh",
                "Gettext Catalog": "text",
                GLSL: "glsl",
                Glyph: "tcl",
                Gnuplot: "text",
                Go: "golang",
                Golo: "text",
                Gosu: "text",
                Grace: "text",
                Gradle: "text",
                "Grammatical Framework": "haskell",
                "Graph Modeling Language": "text",
                "Graphviz (DOT)": "text",
                Groff: "text",
                Groovy: "groovy",
                "Groovy Server Pages": "jsp",
                Hack: "php",
                Haml: "haml",
                Handlebars: "handlebars",
                Harbour: "text",
                Haskell: "haskell",
                Haxe: "haxe",
                HTML: "html",
                "HTML+Django": "django",
                "HTML+ERB": "html_ruby",
                "HTML+PHP": "php",
                HTTP: "text",
                Hy: "clojure",
                IDL: "text",
                Idris: "text",
                "IGOR Pro": "text",
                "Inform 7": "text",
                INI: "ini",
                "Inno Setup": "text",
                Io: "io",
                Ioke: "text",
                "IRC log": "text",
                Isabelle: "text",
                J: "text",
                Jade: "jade",
                Jasmin: "java",
                Java: "java",
                "Java Server Pages": "jsp",
                JavaScript: "javascript",
                JSON: "json",
                JSON5: "javascript",
                JSONiq: "jsoniq",
                JSONLD: "javascript",
                Julia: "julia",
                Kit: "html",
                Kotlin: "text",
                KRL: "text",
                LabVIEW: "text",
                Lasso: "text",
                Latte: "smarty",
                Less: "less",
                LFE: "lisp",
                LilyPond: "text",
                Liquid: "liquid",
                "Literate Agda": "text",
                "Literate CoffeeScript": "text",
                "Literate Haskell": "text",
                LiveScript: "livescript",
                LLVM: "text",
                Logos: "text",
                Logtalk: "text",
                LOLCODE: "text",
                LookML: "yaml",
                LoomScript: "text",
                LSL: "lsl",
                Lua: "lua",
                M: "lisp",
                Makefile: "makefile",
                Mako: "text",
                Markdown: "markdown",
                Mask: "mask",
                Mathematica: "text",
                Matlab: "matlab",
                "Maven POM": "xml",
                Max: "json",
                MediaWiki: "text",
                Mercury: "prolog",
                MiniD: "text",
                Mirah: "ruby",
                Monkey: "text",
                Moocode: "text",
                MoonScript: "text",
                MTML: "html",
                mupad: "text",
                Myghty: "text",
                Nemerle: "text",
                nesC: "text",
                NetLogo: "lisp",
                Nginx: "text",
                Nimrod: "text",
                Ninja: "text",
                Nit: "text",
                Nix: "nix",
                NSIS: "text",
                Nu: "scheme",
                NumPy: "text",
                ObjDump: "assembly_x86",
                "Objective-C": "objectivec",
                "Objective-C++": "objectivec",
                "Objective-J": "text",
                OCaml: "ocaml",
                Omgrofl: "text",
                ooc: "text",
                Opa: "text",
                Opal: "text",
                OpenCL: "c_cpp",
                "OpenEdge ABL": "text",
                OpenSCAD: "text",
                Org: "text",
                Ox: "text",
                Oxygene: "text",
                Oz: "text",
                Pan: "text",
                Papyrus: "text",
                Parrot: "text",
                "Parrot Assembly": "text",
                "Parrot Internal Representation": "text",
                Pascal: "pascal",
                PAWN: "c_cpp",
                Perl: "perl",
                Perl6: "perl",
                PHP: "php",
                PigLatin: "text",
                Pike: "text",
                Pod: "perl",
                PogoScript: "text",
                PostScript: "text",
                PowerShell: "powershell",
                Processing: "text",
                Prolog: "prolog",
                "Propeller Spin": "text",
                "Protocol Buffer": "protobuf",
                "Public Key": "text",
                Puppet: "text",
                "Pure Data": "text",
                PureBasic: "text",
                PureScript: "haskell",
                Python: "python",
                "Python traceback": "text",
                QMake: "text",
                QML: "text",
                R: "r",
                Racket: "lisp",
                "Ragel in Ruby Host": "text",
                RAML: "yaml",
                "Raw token data": "text",
                RDoc: "rdoc",
                REALbasic: "text",
                Rebol: "text",
                Red: "text",
                Redcode: "text",
                reStructuredText: "text",
                RHTML: "rhtml",
                RMarkdown: "markdown",
                RobotFramework: "text",
                Rouge: "clojure",
                Ruby: "ruby",
                Rust: "rust",
                Sage: "python",
                SaltStack: "yaml",
                SAS: "text",
                Sass: "sass",
                Scala: "scala",
                Scaml: "text",
                Scheme: "scheme",
                Scilab: "text",
                SCSS: "scss",
                Self: "text",
                Shell: "sh",
                ShellSession: "sh",
                Shen: "text",
                Slash: "text",
                Slim: "text",
                Smalltalk: "text",
                Smarty: "smarty",
                SourcePawn: "text",
                SQF: "text",
                SQL: "sql",
                Squirrel: "c_cpp",
                "Standard ML": "text",
                Stata: "text",
                STON: "lisp",
                Stylus: "stylus",
                SuperCollider: "text",
                Swift: "text",
                SystemVerilog: "verilog",
                Tcl: "tcl",
                Tcsh: "sh",
                Tea: "text",
                TeX: "tex",
                Text: "text",
                Textile: "textile",
                Thrift: "text",
                TOML: "toml",
                Turing: "text",
                Twig: "twig",
                TXL: "text",
                TypeScript: "typescript",
                "Unified Parallel C": "c_cpp",
                UnrealScript: "java",
                Vala: "vala",
                VCL: "perl",
                Verilog: "verilog",
                VHDL: "vhdl",
                VimL: "text",
                "Visual Basic": "text",
                Volt: "d",
                WebIDL: "text",
                wisp: "clojure",
                xBase: "text",
                XC: "c_cpp",
                XML: "xml",
                Xojo: "text",
                XProc: "xml",
                XQuery: "xquery",
                XS: "c_cpp",
                XSLT: "xml",
                Xtend: "text",
                YAML: "yaml",
                Zephir: "php",
                Zimpl: "text"
            }
        };
        return syntax;
    });
});